version: "3.0"

services:
  nginx:
    image: nginx
    volumes:
     - ./:/var/www
     - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    networks:
     - front-tier
     - back-tier


  # Our Redis service:
  redis:
    image: redis:3.2.4-alpine
    ports:
      # We'll bind our host's port 6379 to redis's port 6379, so we can use
      # Redis Desktop Manager (or other tools) with it:
      - 6379:6379
    volumes:
      # We'll mount the 'redis-data' volume into the location redis stores it's data:
      - redis-data:/var/lib/redis
    command: redis-server --appendonly yes

  php:
    image: sierratecnologia/php:7.1
    ports:
     - "9000:9000"
    restart: always
    command: bash -c "sed -i \"s/memory_limit = 128M/memory_limit = 1024M/\" /usr/local/etc/php/php.ini && sed -i \"s/short_open_tag = Off/short_open_tag = On/\" /usr/local/etc/php/php.ini && sed -i \"s/max_execution_time = 30/max_execution_time = 300/\" /usr/local/etc/php/php.ini && php-fpm"
    environment:
     - XDEBUG_CONFIG=remote_host=172.17.0.1
    volumes:
     - ./:/var/www
    depends_on:
     - postgres
    networks:
      - front-tier
      - back-tier

  mysql:
    image: mysql:5.7
    volumes:
     - db_data:/var/lib/mysql
     - ./dabatase/dumps:/dumps
    environment:
     MYSQL_ROOT_PASSWORD: A123456
     MYSQL_DATABASE: nlsgroup_ee
     MYSQL_USER: nlsgroup
     MYSQL_PASSWORD: A123456
    networks:
     - back-tier

  phpmyadmin:
    image: sierratecnologia/phpmyadmin:4.7
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    restart: always
    ports:
     - "8080:80"
    networks:
     - front-tier
     - back-tier

volumes:
 db-data:

networks:
 front-tier:
 back-tier:
